apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: ghcr.io/ayushquasar/auth-service
  newName: ghcr.io/ayushquasar/auth-service
  newTag: a6854008af51a0d10c8794fd422d0bb734a824e5
