apiVersion: apps/v1
kind: Deployment
metadata:
  name: history-service
  namespace: production-retail
  labels:
    app: history-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: history-service
  template:
    metadata:
      labels:
        app: history-service
    spec:
      serviceAccountName: history-service
      containers:
        - name: history-service
          image: ghcr.io/ayushQuasar/history-service:latest
          ports:
            - containerPort: 8084
          env:
            - name: POSTGRES_HOST
              value: "postgres-service"
            - name: POSTGRES_DB
              value: "retail_db"
            - name: POSTGRES_USER
              value: "retail_user"
            - name: POSTGRES_PASSWORD
              value: "retail_pass"
            - name: KAFKA_SERVERS
              value: "kafka-service:9092"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://jaeger-collector.istio-system:4318"
            - name: OTEL_SERVICE_NAME
              value: "history-service"
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 300m
              memory: 512Mi
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8084
            failureThreshold: 20
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8084
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8084
            periodSeconds: 15
