apiVersion: v1
kind: Service
metadata:
  name: history-service
  namespace: production-retail
  labels:
    app: history-service
spec:
  ports:
    - name: http
      port: 8084
      targetPort: 8084
  selector:
    app: history-service
  type: ClusterIP
