apiVersion: v1
kind: Service
metadata:
  name: storefront-service
  namespace: production-retail
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: storefront
  type: ClusterIP
