apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - jaeger.yaml
  - telemetry.yaml
  - http-routes.yaml
  - destination-rules.yaml
  - waypoint.yaml
  - servicemonitors.yaml
