apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istio-waypoint
  namespace: production-retail
  labels:
    release: rancher-monitoring
spec:
  selector:
    matchExpressions:
      - key: istio.io/waypoint-for
        operator: Exists
  namespaceSelector:
    matchNames:
      - production-retail
  endpoints:
    - port: http-envoy-prom
      path: /stats/prometheus
      interval: 30s
      scrapeTimeout: 10s
---
apiVersion: v1
kind: Service
metadata:
  name: istio-waypoint-metrics
  namespace: production-retail
  labels:
    istio.io/waypoint-for: service
spec:
  selector:
    istio.io/waypoint-for: service
  ports:
    - name: http-envoy-prom
      port: 15090
      targetPort: 15090
      protocol: TCP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istio-ztunnel
  namespace: istio-system
  labels:
    release: rancher-monitoring
spec:
  selector:
    matchLabels:
      app: ztunnel
  namespaceSelector:
    matchNames:
      - istio-system
  endpoints:
    - port: ztunnel-stats
      path: /stats/prometheus
      interval: 30s
      scrapeTimeout: 10s
