apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: ghcr.io/ayushquasar/api-gateway
  newName: ghcr.io/ayushquasar/api-gateway
  newTag: 87af4142b0218068b0f46b36ab6de724308af87c
